---
- name: "Move files to server"
  become: true
  copy:
    src: /root/project/backend/
    dest: /home/ubuntu/app

- name: Start PM2
  shell: |
    cd /home/ubuntu/app
    pm2 start npm --name backend -- start
  

