---
- name: Move files to server
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/app

#- name: Run migrations
#  shell: |
#    cd /home/ubuntu/app/backend
#    sudo npm run migrations

- name: Start PM2
  shell: |
    cd /home/ubuntu/app/backend
    pm2 start npm -- run start
  

